[_]
schema-version = "0.2"

[[io.buildpacks.build.env]]
name = "HUSKY"
value = "0"

[[io.buildpacks.build.env]]
name = "NODE_ENV"
value = "production"

[[io.buildpacks.build.env]]
name = "NEXT_TELEMETRY_DISABLED"
value = "1"
