apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-credentials
  labels:
    app.kubernetes.io/name: postgres
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao-backend
    kind: ClusterSecretStore
  target:
    name: postgres-credentials
    deletionPolicy: Retain
  data:
    - secretKey: password
      remoteRef:
        key: secret/family-picnic-dev/postgres
        property: password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nextjs-secrets
  labels:
    app.kubernetes.io/name: nextjs
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao-backend
    kind: ClusterSecretStore
  target:
    name: nextjs-secrets
    deletionPolicy: Retain
  data:
    - secretKey: database-url
      remoteRef:
        key: secret/family-picnic-dev/nextjs
        property: database-url
    - secretKey: auth-google-id
      remoteRef:
        key: secret/family-picnic-dev/nextjs
        property: auth-google-id
    - secretKey: auth-google-secret
      remoteRef:
        key: secret/family-picnic-dev/nextjs
        property: auth-google-secret
    - secretKey: nextauth-secret
      remoteRef:
        key: secret/family-picnic-dev/nextjs
        property: nextauth-secret
    - secretKey: sendgrid-api-key
      remoteRef:
        key: secret/family-picnic-dev/nextjs
        property: sendgrid-api-key
    - secretKey: twilio-account-sid
      remoteRef:
        key: secret/family-picnic-dev/nextjs
        property: twilio-account-sid
    - secretKey: twilio-auth-token
      remoteRef:
        key: secret/family-picnic-dev/nextjs
        property: twilio-auth-token
    - secretKey: twilio-phone-number
      remoteRef:
        key: secret/family-picnic-dev/nextjs
        property: twilio-phone-number
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: photoprism-credentials
  labels:
    app.kubernetes.io/name: photoprism
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao-backend
    kind: ClusterSecretStore
  target:
    name: photoprism-credentials
    deletionPolicy: Retain
  data:
    - secretKey: admin-password
      remoteRef:
        key: secret/family-picnic-dev/photoprism
        property: admin-password
