apiVersion: apps/v1
kind: Deployment
metadata:
  name: photoprism
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: photoprism
          resources:
            requests:
              cpu: 500m
              memory: 2Gi
            limits:
              cpu: '4'
              memory: 8Gi
