import { z } from 'zod';

// FPP-43: Zod schemas for the admin PDF attachment CRUD endpoints.
// Size is capped at 10 MB to match the FPP-2 acceptance criterion
// and the S3 presigned PUT's `ContentLength` validation. Filename
// is capped at 200 chars to mirror PhotoPrism and avoid pathological
// uploads. `contentType` is the wire `Content-Type` the admin's
// browser sent; we only accept `application/pdf`.

export const PDF_MAX_BYTES = 10 * 1024 * 1024;
export const PDF_MAX_FILENAME_LENGTH = 200;

export const eventAttachmentCreateSchema = z.object({
  eventId: z.string().min(1, 'Event ID is required'),
  // Server-generated by the upload-url endpoint, but the admin posts
  // the returned key back here so the server can confirm it matches
  // what was issued. Keeps the upload-URL flow stateless.
  key: z.string().min(1, 'Attachment key is required'),
  filename: z
    .string()
    .trim()
    .min(1, 'Filename is required')
    .max(
      PDF_MAX_FILENAME_LENGTH,
      `Filename must be ${PDF_MAX_FILENAME_LENGTH} characters or fewer`,
    ),
  contentType: z.literal('application/pdf'),
  sizeBytes: z
    .number()
    .int()
    .positive('Size must be positive')
    .max(PDF_MAX_BYTES, `File must be ${PDF_MAX_BYTES / (1024 * 1024)} MB or smaller`),
});

export const eventAttachmentRenameSchema = z
  .object({
    filename: z
      .string()
      .trim()
      .min(1, 'Filename is required')
      .max(
        PDF_MAX_FILENAME_LENGTH,
        `Filename must be ${PDF_MAX_FILENAME_LENGTH} characters or fewer`,
      ),
  })
  .strict();

export const eventAttachmentUploadUrlSchema = z.object({
  eventId: z.string().min(1, 'Event ID is required'),
  filename: z
    .string()
    .trim()
    .min(1, 'Filename is required')
    .max(
      PDF_MAX_FILENAME_LENGTH,
      `Filename must be ${PDF_MAX_FILENAME_LENGTH} characters or fewer`,
    ),
  contentType: z.literal('application/pdf'),
  sizeBytes: z
    .number()
    .int()
    .positive('Size must be positive')
    .max(PDF_MAX_BYTES, `File must be ${PDF_MAX_BYTES / (1024 * 1024)} MB or smaller`),
});

export type EventAttachmentCreateInput = z.infer<typeof eventAttachmentCreateSchema>;
export type EventAttachmentRenameInput = z.infer<typeof eventAttachmentRenameSchema>;
export type EventAttachmentUploadUrlInput = z.infer<typeof eventAttachmentUploadUrlSchema>;
