apiVersion: v1
kind: ConfigMap
metadata:
  name: nextjs-env
  labels:
    app.kubernetes.io/name: nextjs
    app.kubernetes.io/component: frontend
data:
  NEXTAUTH_URL: https://family-picnic.dev.qubitquilt.dev
  NODE_ENV: production
  NEXT_PUBLIC_APP_URL: https://family-picnic.dev.qubitquilt.dev
  S3_BUCKET: family-picnic-photos
  S3_REGION: us-east-1
  S3_ENDPOINT: ''
  PHOTOPRISM_URL: http://photoprism:8080
