apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: family-picnic

commonLabels:
  app.kubernetes.io/part-of: family-picnic

resources:
  - namespace.yaml
  - nextjs.yaml
  - postgres.yaml
  - photoprism.yaml
  - configmap.yaml
  - ingressroute.yaml
  - ingress.yaml
