#!/usr/bin/env bash
#
# populate-openbao-secrets.sh
#
# Populates the OpenBao secret paths required by the family-picnic-dev
# ArgoCD Application. Runs `bao kv put` via `kubectl exec` into the
# openbao-0 pod, so no local OpenBao CLI is required.
#
# Generated values are also written to ./family-picnic-dev-secrets.txt
# (mode 0600) so they can be referenced later. That file is gitignored.
#
# Usage:
#   ./scripts/populate-openbao-secrets.sh
#
# Env overrides:
#   OPENBAO_NAMESPACE  default: security
#   OPENBAO_POD        default: openbao-0
#   SECRET_PREFIX      default: secret/family-picnic-dev
#   LOCAL_OUTPUT       default: ./family-picnic-dev-secrets.txt

set -euo pipefail

OPENBAO_NAMESPACE="${OPENBAO_NAMESPACE:-security}"
OPENBAO_POD="${OPENBAO_POD:-openbao-0}"
SECRET_PREFIX="${SECRET_PREFIX:-secret/family-picnic-dev}"
LOCAL_OUTPUT="${LOCAL_OUTPUT:-./family-picnic-dev-secrets.txt}"
ENV_DEV_OUTPUT="${ENV_DEV_OUTPUT:-./.env.dev}"
APP_DOMAIN="${APP_DOMAIN:-family-picnic.dev.qubitquilt.dev}"
PHOTOS_DOMAIN="${PHOTOS_DOMAIN:-photos.family-picnic.dev.qubitquilt.dev}"

# --- preflight ---------------------------------------------------------------

if ! command -v kubectl >/dev/null 2>&1; then
  echo "ERROR: kubectl not found in PATH" >&2
  exit 1
fi

if ! command -v openssl >/dev/null 2>&1; then
  echo "ERROR: openssl not found in PATH" >&2
  exit 1
fi

if ! kubectl -n "$OPENBAO_NAMESPACE" get pod "$OPENBAO_POD" >/dev/null 2>&1; then
  echo "ERROR: pod $OPENBAO_POD not found in namespace $OPENBAO_NAMESPACE" >&2
  echo "Set OPENBAO_POD / OPENBAO_NAMESPACE if it lives elsewhere." >&2
  exit 1
fi

# --- helpers -----------------------------------------------------------------

bao_exec() {
  kubectl -n "$OPENBAO_NAMESPACE" exec -i "$OPENBAO_POD" -- bao "$@"
}

gen_secret() {
  local bytes="${1:-32}"
  openssl rand -base64 "$bytes" 2>/dev/null | tr -d '/+=\n' | head -c "$bytes"
}

# --- generate ----------------------------------------------------------------

echo "==> Generating random secrets for ${SECRET_PREFIX}/{postgres,nextjs,photoprism}"

PG_PASS="$(gen_secret 32)"
NEXTAUTH_SECRET="$(gen_secret 32)"
PHOTOPRISM_ADMIN_PASS="$(gen_secret 16)"

DATABASE_URL="postgresql://postgres:${PG_PASS}@postgres:5432/familypicnic?schema=public"

# --- write to OpenBao --------------------------------------------------------

echo "==> Writing ${SECRET_PREFIX}/postgres"
bao_exec kv put "${SECRET_PREFIX}/postgres" \
  password="$PG_PASS" \
  >/dev/null

echo "==> Writing ${SECRET_PREFIX}/nextjs"
bao_exec kv put "${SECRET_PREFIX}/nextjs" \
  database-url="$DATABASE_URL" \
  auth-google-id="" \
  auth-google-secret="" \
  nextauth-secret="$NEXTAUTH_SECRET" \
  sendgrid-api-key="" \
  twilio-account-sid="" \
  twilio-auth-token="" \
  >/dev/null

echo "==> Writing ${SECRET_PREFIX}/photoprism"
bao_exec kv put "${SECRET_PREFIX}/photoprism" \
  admin-password="$PHOTOPRISM_ADMIN_PASS" \
  >/dev/null

# --- save local copy ---------------------------------------------------------

cat > "$LOCAL_OUTPUT" <<EOF
# Generated by scripts/populate-openbao-secrets.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# DO NOT COMMIT. Keep this file local.
#
PG_PASS=$PG_PASS
NEXTAUTH_SECRET=$NEXTAUTH_SECRET
PHOTOPRISM_ADMIN_PASS=$PHOTOPRISM_ADMIN_PASS
DATABASE_URL=$DATABASE_URL
EOF
chmod 600 "$LOCAL_OUTPUT"

# --- write .env.dev for local dev --------------------------------------------

cat > "$ENV_DEV_OUTPUT" <<EOF
# Generated by scripts/populate-openbao-secrets.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Local dev .env. Matches the OpenBao values pushed to ${SECRET_PREFIX}/*.
#
# To use the in-cluster postgres, forward the service first:
#   kubectl port-forward svc/postgres 5432:5432 -n family-picnic-dev
#
# To use the in-cluster photoprism, forward it too:
#   kubectl port-forward svc/photoprism 2342:8080 -n family-picnic-dev

# --- Database ---
DATABASE_URL="postgresql://postgres:${PG_PASS}@localhost:5432/familypicnic-dev?schema=public"

# --- NextAuth ---
NEXTAUTH_URL="http://localhost:3000"
NEXTAUTH_SECRET="${NEXTAUTH_SECRET}"

# --- Dev auth bypass (gated by DEV_AUTH_ENABLED) ---
DEV_AUTH_ENABLED=true
DEV_AUTH_USERNAME=admin
DEV_AUTH_PASSWORD="${PHOTOPRISM_ADMIN_PASS}"

# --- Google OAuth (leave empty for now) ---
AUTH_GOOGLE_ID=""
AUTH_GOOGLE_SECRET=""

# --- Twilio (leave empty) ---
TWILIO_ACCOUNT_SID=""
TWILIO_AUTH_TOKEN=""
TWILIO_PHONE_NUMBER=""

# --- SendGrid (leave empty) ---
SENDGRID_API_KEY=""
SENDGRID_FROM_EMAIL="dev@${APP_DOMAIN}"

# --- S3 (using photoprism via Next.js; no S3 in dev) ---
S3_ENDPOINT=""
S3_BUCKET="family-picnic-dev"
S3_ACCESS_KEY=""
S3_SECRET_KEY=""
S3_PUBLIC_URL=""

# --- PhotoPrism ---
PHOTOPRISM_URL="http://localhost:2342"
PHOTOPRISM_API_KEY="${PHOTOPRISM_ADMIN_PASS}"

# --- Observability ---
LOG_LEVEL=debug
SENTRY_DSN=""
OTEL_EXPORTER_OTLP_ENDPOINT=""

# --- Cron ---
CRON_SECRET="${NEXTAUTH_SECRET}"
EOF
chmod 600 "$ENV_DEV_OUTPUT"

echo ""
echo "==> All three OpenBao paths written under ${SECRET_PREFIX}"
echo "==> Raw values: $LOCAL_OUTPUT (mode 0600)"
echo "==> .env.dev:   $ENV_DEV_OUTPUT (mode 0600)"
echo ""
echo "Next steps:"
echo "  1. Forward cluster services to localhost:"
echo "       kubectl port-forward svc/postgres 5432:5432 -n family-picnic-dev &"
echo "       kubectl port-forward svc/photoprism 2342:8080 -n family-picnic-dev &"
echo "  2. Force the ExternalSecret to refresh (or wait up to 1m):"
echo "       kubectl annotate externalsecret -n family-picnic-dev --all force-sync=\$(date +%s)"
echo "  3. Watch the pods come up:"
echo "       kubectl get pods -n family-picnic-dev -w"
echo "  4. Visit https://${APP_DOMAIN}"
