- op: replace
  path: /spec/template/spec/containers/0/readinessProbe/httpGet/path
  value: /api/auth/session
- op: replace
  path: /spec/template/spec/containers/0/livenessProbe/httpGet/path
  value: /api/auth/session
- op: replace
  path: /spec/template/spec/containers/0/readinessProbe/initialDelaySeconds
  value: 30
- op: replace
  path: /spec/template/spec/containers/0/livenessProbe/initialDelaySeconds
  value: 60
- op: replace
  path: /spec/template/spec/containers/0/readinessProbe/timeoutSeconds
  value: 5
- op: replace
  path: /spec/template/spec/containers/0/livenessProbe/timeoutSeconds
  value: 5
- op: replace
  path: /spec/template/spec/containers/0/readinessProbe/periodSeconds
  value: 30
- op: replace
  path: /spec/template/spec/containers/0/livenessProbe/periodSeconds
  value: 60
- op: replace
  path: /spec/template/spec/containers/0/livenessProbe/failureThreshold
  value: 5
