name: Docker

on:
  push:
    tags:
      - 'v*'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: family-picnic-runner-set
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v5

      - name: Extract metadata
        id: meta
        run: |
          echo "tags=${{ github.ref_name }}" >> $GITHUB_OUTPUT
          echo "labels=org.opencontainers.image.title=${{ github.repository }} \
            org.opencontainers.image.version=${{ github.ref_name }} \
            org.opencontainers.image.revision=${{ github.sha }} \
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}" >> $GITHUB_OUTPUT

      - name: Log in to Container Registry
        uses: redhat-actions/buildah-login@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        id: build
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          containerfiles: |
            ./Dockerfile
          platforms: linux/arm64

      - name: Push
        id: push
        uses: redhat-actions/buildah-push@v1
        with:
          image: ${{ steps.build.outputs.image }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          extra-args: |
            --platform=linux/arm64

      - name: Image digest
        run: 'echo "Pushed with tag: ${{ steps.meta.outputs.tags }}"'
